# ⚠️  DEPRECATED: Docker-based Temporal setup
# 
# This file is no longer recommended for local development.
# 
# ✅ NEW APPROACH: Use Temporal CLI instead
# 
# Install: brew install temporal
# Start:   temporal server start-dev --ui-port 8088
# 
# Benefits of Temporal CLI:
# - ✅ Native Apple Silicon support (no ARM64/AMD64 issues)
# - ✅ Zero configuration required
# - ✅ Instant startup (seconds vs minutes)
# - ✅ Official Temporal recommendation
# - ✅ Built-in SQLite persistence
# 
# See: media-planner-infra/TEMPORAL_SETUP.md

version: '3.8'

networks:
  temporal-network:
    driver: bridge
    name: temporal-network

volumes:
  temporal-postgres-data:
    driver: local

services:
  # PostgreSQL Database for Temporal persistence
  temporal-postgres:
    image: postgres:15-alpine
    platform: linux/amd64
    container_name: temporal-postgres
    environment:
      POSTGRES_DB: temporal
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
    volumes:
      - temporal-postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - temporal-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U temporal"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Temporal Server with auto-setup (minimal without ES)
  temporal-server:
    image: temporalio/auto-setup:1.22.4
    platform: linux/amd64
    container_name: temporal-server
    depends_on:
      temporal-postgres:
        condition: service_healthy
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=temporal-postgres
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
      - ENABLE_ES=false
      - TEMPORAL_CLI_ADDRESS=temporal-server:7233
      - TEMPORAL_ADDRESS=0.0.0.0:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000,http://localhost:8080,https://lovable.dev,https://*.lovable.app
    ports:
      - "7233:7233"   # gRPC endpoint
    networks:
      - temporal-network
    healthcheck:
      test: ["CMD", "tctl", "--address", "temporal-server:7233", "cluster", "health"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: unless-stopped

  # Temporal Web UI
  temporal-web:
    image: temporalio/web:2.21.3
    platform: linux/amd64
    container_name: temporal-web
    depends_on:
      temporal-server:
        condition: service_healthy
    environment:
      - TEMPORAL_ADDRESS=temporal-server:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000,http://localhost:8080,https://lovable.dev,https://*.lovable.app
      - TEMPORAL_PERMIT_WRITE_API=true
    ports:
      - "8088:8088"
    networks:
      - temporal-network
    restart: unless-stopped 